const response = {
  "Status": true,
  "ErrorType": null,
  "TopicInfo": {
    "TopicID": "3b5ffb9354554f5eab909c2256dc7ad2i2u3",
    "TopicSubject": "Regression Testing,Regression Testing,Regression Testing",
    "TopicDescription": "Regression Testing Regression Testing Regression Testing Regression Testing Regression Testing Regression Testing Regression TestingRegression Testing",
    "PostedOn": "Nov-21-2025 11:06 AM",
    "TopicPostedUserName": "Jyoti A",
    "TopicPostedUserID": "3",
    "TopicPostedUserPic": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/2\/3\/profilepicture\/2_3_270b5f35-b502-41c5-baae-edb5fab13ca0profilemock.png?expiry=1773417453&signature=U0lmc1FxV2JwdkI3OTB3amNQVnNWaHJnNHRHRmJGM3huOUpiM1lBOVIvUT18Q29tbXVuaWNhdGlvbg%3D%3D&b=87621",
    "TopicPostedUserStatus": "",
    "TopicLikes": 1,
    "TopicDislikes": 0,
    "TopicReplies": 3,
    "TopicCategory": "Testing",
    "TopicCategoryID": "d0aaac3b1a234ad2bf180150328bdc5ai2u3",
    "UserTopicStatus": "",
    "TopicAttachmentList": null,
    "AllowReply": true,
    "TopicReplyList": [
      {
        "ReplyDescription": "test user",
        "ReplyID": "0e523253a99648eebc7bee64f9970d66i2u29118",
        "ReplyPostedOn": "Dec-29-2025 01:23 PM",
        "ReplyPostedUserName": "Kirankumar K",
        "ReplyPostedUserID": "29118",
        "ReplyPostedUserPic": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/26\/29118\/profilepicture\/26_29118_bcd0f183-a9f1-4ff7-b7a1-5e8c0bb01b03.png?expiry=1773417453&signature=dzF2K25ITURCYURXL3lGaWZEbjNHVUdBWHZNVFNsU1hCVk16SjZ4WjFjYz18Q29tbXVuaWNhdGlvbg%3D%3D&b=64607",
        "ReplyPostedUserStatus": "",
        "ReplyLikes": 1,
        "ReplyDislikes": 0,
        "UserReplyStatus": "",
        "ReplyAttachmentList": null,
        "Reply4Replies": 1,
        "AllowReply4Reply": true,
        "Reply4ReplyList": [
          {
            "ReplyDescription": "test",
            "ReplyID": "24eb0007bba14e19931b6713199dcbc1i2u29118",
            "ReplyPostedOn": "Jan-05-2026 01:26 PM",
            "ReplyPostedUserName": "Kirankumar K",
            "ReplyPostedUserID": "29118",
            "ReplyPostedUserPic": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/26\/29118\/profilepicture\/26_29118_bcd0f183-a9f1-4ff7-b7a1-5e8c0bb01b03.png?expiry=1773417453&signature=dzF2K25ITURCYURXL3lGaWZEbjNHVUdBWHZNVFNsU1hCVk16SjZ4WjFjYz18Q29tbXVuaWNhdGlvbg%3D%3D&b=64607",
            "ReplyPostedUserStatus": "",
            "ReplyLikes": 0,
            "ReplyDislikes": 0,
            "UserReplyStatus": "",
            "ReplyAttachmentList": null,
            "Reply4Replies": 0,
            "AllowReply4Reply": true,
            "Reply4ReplyList": [],
            "Reply4ReplyMoreButtonDisplay": false,
            "IsSensitiveReply": false,
            "IsSpamReply": false,
            "SensitiveKeyword": "",
            "ProfileRingCode": "",
            "ReplayAttachmentDetailList": [],
          },
        ],
        "Reply4ReplyMoreButtonDisplay": false,
        "IsSensitiveReply": false,
        "IsSpamReply": false,
        "SensitiveKeyword": "",
        "ProfileRingCode": "",
        "ReplayAttachmentDetailList": [],
      },
      {
        "ReplyDescription": "hello",
        "ReplyID": "8a12103c44834103a9052b322d26683ei2u29118",
        "ReplyPostedOn": "Dec-29-2025 01:10 PM",
        "ReplyPostedUserName": "Kirankumar K",
        "ReplyPostedUserID": "29118",
        "ReplyPostedUserPic": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/26\/29118\/profilepicture\/26_29118_bcd0f183-a9f1-4ff7-b7a1-5e8c0bb01b03.png?expiry=1773417453&signature=dzF2K25ITURCYURXL3lGaWZEbjNHVUdBWHZNVFNsU1hCVk16SjZ4WjFjYz18Q29tbXVuaWNhdGlvbg%3D%3D&b=64607",
        "ReplyPostedUserStatus": "",
        "ReplyLikes": 1,
        "ReplyDislikes": 0,
        "UserReplyStatus": "",
        "ReplyAttachmentList": null,
        "Reply4Replies": 2,
        "AllowReply4Reply": true,
        "Reply4ReplyList": [
          {
            "ReplyDescription": "Jamshed",
            "ReplyID": "73d64aa8941542d79193e12834b8f0a9i2u29118",
            "ReplyPostedOn": "Dec-29-2025 01:49 PM",
            "ReplyPostedUserName": "Kirankumar K",
            "ReplyPostedUserID": "29118",
            "ReplyPostedUserPic": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/26\/29118\/profilepicture\/26_29118_bcd0f183-a9f1-4ff7-b7a1-5e8c0bb01b03.png?expiry=1773417453&signature=dzF2K25ITURCYURXL3lGaWZEbjNHVUdBWHZNVFNsU1hCVk16SjZ4WjFjYz18Q29tbXVuaWNhdGlvbg%3D%3D&b=64607",
            "ReplyPostedUserStatus": "",
            "ReplyLikes": 0,
            "ReplyDislikes": 0,
            "UserReplyStatus": "",
            "ReplyAttachmentList": null,
            "Reply4Replies": 0,
            "AllowReply4Reply": true,
            "Reply4ReplyList": [],
            "Reply4ReplyMoreButtonDisplay": false,
            "IsSensitiveReply": false,
            "IsSpamReply": false,
            "SensitiveKeyword": "",
            "ProfileRingCode": "",
            "ReplayAttachmentDetailList": [],
          },
          {
            "ReplyDescription": "test test test",
            "ReplyID": "680868cfece248838d2e3c0bcd59db88i2u29118",
            "ReplyPostedOn": "Dec-29-2025 01:48 PM",
            "ReplyPostedUserName": "Kirankumar K",
            "ReplyPostedUserID": "29118",
            "ReplyPostedUserPic": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/26\/29118\/profilepicture\/26_29118_bcd0f183-a9f1-4ff7-b7a1-5e8c0bb01b03.png?expiry=1773417453&signature=dzF2K25ITURCYURXL3lGaWZEbjNHVUdBWHZNVFNsU1hCVk16SjZ4WjFjYz18Q29tbXVuaWNhdGlvbg%3D%3D&b=64607",
            "ReplyPostedUserStatus": "",
            "ReplyLikes": 0,
            "ReplyDislikes": 0,
            "UserReplyStatus": "",
            "ReplyAttachmentList": null,
            "Reply4Replies": 0,
            "AllowReply4Reply": true,
            "Reply4ReplyList": [],
            "Reply4ReplyMoreButtonDisplay": false,
            "IsSensitiveReply": false,
            "IsSpamReply": false,
            "SensitiveKeyword": "",
            "ProfileRingCode": "",
            "ReplayAttachmentDetailList": [],
          },
        ],
        "Reply4ReplyMoreButtonDisplay": false,
        "IsSensitiveReply": false,
        "IsSpamReply": false,
        "SensitiveKeyword": "",
        "ProfileRingCode": "",
        "ReplayAttachmentDetailList": [],
      },
      {
        "ReplyDescription": "test",
        "ReplyID": "da89e1cf109d42cc8074f93d70c6adbdi2u29118",
        "ReplyPostedOn": "Dec-29-2025 01:06 PM",
        "ReplyPostedUserName": "Kirankumar K",
        "ReplyPostedUserID": "29118",
        "ReplyPostedUserPic": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/26\/29118\/profilepicture\/26_29118_bcd0f183-a9f1-4ff7-b7a1-5e8c0bb01b03.png?expiry=1773417453&signature=dzF2K25ITURCYURXL3lGaWZEbjNHVUdBWHZNVFNsU1hCVk16SjZ4WjFjYz18Q29tbXVuaWNhdGlvbg%3D%3D&b=64607",
        "ReplyPostedUserStatus": "",
        "ReplyLikes": 1,
        "ReplyDislikes": 0,
        "UserReplyStatus": "",
        "ReplyAttachmentList": null,
        "Reply4Replies": 0,
        "AllowReply4Reply": true,
        "Reply4ReplyList": [],
        "Reply4ReplyMoreButtonDisplay": false,
        "IsSensitiveReply": false,
        "IsSpamReply": false,
        "SensitiveKeyword": "",
        "ProfileRingCode": "",
        "ReplayAttachmentDetailList": [],
      },
    ],
    "ReplyMoreButtonDisplay": false,
    "TopicAudienceList": [
      {"TopicAudienceType": "All", "TopicAudienceIDList": null},
    ],
    "AllowReply4Reply": true,
    "IsSensitiveTopic": false,
    "IsSpamTopic": false,
    "SensitiveKeyword": "",
    "IsSubscribed": false,
    "ForumCommunication": [
      {"CommunicationType": "Push", "Status": false, "ComponentType": null, "ComponentID": null},
      {"CommunicationType": "Email", "Status": false, "ComponentType": null, "ComponentID": null},
      {"CommunicationType": "WeeklyEmail", "Status": false, "ComponentType": null, "ComponentID": null},
      {"CommunicationType": "BiWeeklyEmail", "Status": false, "ComponentType": null, "ComponentID": null},
    ],
    "IsFeaturedTopic": true,
    "IsPinnedTopic": false,
    "Call4ActionLabel": "iCent",
    "Call4ActionUrl": "https:\/\/icentapp.com",
    "Call4ActionType": "WebURL",
    "Call4ActionID": "130",
    "LikeUnlikeApplicable": true,
    "CommentsApplicable": true,
    "EnableLike": true,
    "EnableUnlike": true,
    "StyleConfig": {
      "Header": {"BackgroundColor": "#1c324e", "FontColor": "#ffffff"},
    },
    "TopicDescriptionHTML": "<p>Regression Testing&nbsp;<\/p>",
    "Call4ActionList": [
      {"ComponentID": "https:\/\/icentapp.com", "ComponentType": "WebURL", "ID": "130", "Label": "iCent", "TopicID": "3b5ffb9354554f5eab909c2256dc7ad2i2u3"},
      {"ComponentID": "831", "ComponentType": "Workshop", "ID": "131", "Label": "Training", "TopicID": "3b5ffb9354554f5eab909c2256dc7ad2i2u3"},
    ],
    "TaggedUser": {
      "Header": "USER",
      "Config": [
        {"UserID": "15", "TaggedUserRole": "QA", "Sequence": 1},
      ],
      "UserInfoList": [
        {
          "ComponentType": "User",
          "ComponentID": "15",
          "FirstName": "Jyoti",
          "LastName": "A",
          "EmailID": "jyoti_qa@neeltesting.com",
          "ProfilePicture": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/2\/public\/f29c17aa-54ce-4385-b4c1-8bbd91f6cd8a.png?expiry=1773417453&signature=WU56Lzc3UmZYN0VKY2g5K0VWRXU0dzVJZmVJUFByZ3UyQ2RQdzZvZTczcz18Q29tbXVuaWNhdGlvbg%3D%3D&b=7621",
          "UserChatEnabled": true,
          "IsUserOnline": true,
          "Description": "Tester",
          "Position": "QA",
          "Organization": "QA",
          "UserPhoneBook": [],
          "SocialMediaList": [
            {"ID": "35", "InstituteId": "2", "Code": "LI", "Url": "https:\/\/www.linkedin.com\/", "Description": ""},
            {"ID": "36", "InstituteId": "2", "Code": "FB", "Url": "https:\/\/www.facebook.com", "Description": ""},
            {"ID": "37", "InstituteId": "2", "Code": "TW", "Url": "https:\/\/www.x.com", "Description": ""},
            {"ID": "38", "InstituteId": "2", "Code": "IG", "Url": "https:\/\/www.Instagram.com\/", "Description": ""},
            {"ID": "39", "InstituteId": "2", "Code": "TH", "Url": "https:\/\/threads.com", "Description": ""},
            {"ID": "40", "InstituteId": "2", "Code": "BS", "Url": "", "Description": ""},
          ],
          "ExchangeContactInfoEnabled": true,
          "UserBio": "Tester",
          "PresenterRole": "QA",
          "WorkshopList": [
            {"PresenterRole": "QA", "WorkshopID": "10337", "WorkshopTitle": "Regression Testing"},
            {"PresenterRole": null, "WorkshopID": "10338", "WorkshopTitle": "Regression Testing [19-02-2026]"},
          ],
          "ProfileRingCode": null,
        },

        {
          "ComponentType": "User",
          "ComponentID": "15",
          "FirstName": "Jyoti",
          "LastName": "A",
          "EmailID": "jyoti_qa@neeltesting.com",
          "ProfilePicture": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/2\/public\/f29c17aa-54ce-4385-b4c1-8bbd91f6cd8a.png?expiry=1773417453&signature=WU56Lzc3UmZYN0VKY2g5K0VWRXU0dzVJZmVJUFByZ3UyQ2RQdzZvZTczcz18Q29tbXVuaWNhdGlvbg%3D%3D&b=7621",
          "UserChatEnabled": true,
          "IsUserOnline": true,
          "Description": "Tester",
          "Position": "QA",
          "Organization": "QA",
          "UserPhoneBook": [],
          "SocialMediaList": [
            {"ID": "35", "InstituteId": "2", "Code": "LI", "Url": "https:\/\/www.linkedin.com\/", "Description": ""},
            {"ID": "36", "InstituteId": "2", "Code": "FB", "Url": "https:\/\/www.facebook.com", "Description": ""},
            {"ID": "37", "InstituteId": "2", "Code": "TW", "Url": "https:\/\/www.x.com", "Description": ""},
            {"ID": "38", "InstituteId": "2", "Code": "IG", "Url": "https:\/\/www.Instagram.com\/", "Description": ""},
            {"ID": "39", "InstituteId": "2", "Code": "TH", "Url": "https:\/\/threads.com", "Description": ""},
            {"ID": "40", "InstituteId": "2", "Code": "BS", "Url": "", "Description": ""},
          ],
          "ExchangeContactInfoEnabled": true,
          "UserBio": "Tester",
          "PresenterRole": "QA",
          "WorkshopList": [
            {"PresenterRole": "QA", "WorkshopID": "10337", "WorkshopTitle": "Regression Testing"},
            {"PresenterRole": null, "WorkshopID": "10338", "WorkshopTitle": "Regression Testing [19-02-2026]"},
          ],
          "ProfileRingCode": null,
        },
        {
          "ComponentType": "User",
          "ComponentID": "15",
          "FirstName": "Jyoti",
          "LastName": "A",
          "EmailID": "jyoti_qa@neeltesting.com",
          "ProfilePicture": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/2\/public\/f29c17aa-54ce-4385-b4c1-8bbd91f6cd8a.png?expiry=1773417453&signature=WU56Lzc3UmZYN0VKY2g5K0VWRXU0dzVJZmVJUFByZ3UyQ2RQdzZvZTczcz18Q29tbXVuaWNhdGlvbg%3D%3D&b=7621",
          "UserChatEnabled": true,
          "IsUserOnline": true,
          "Description": "Tester",
          "Position": "QA",
          "Organization": "QA",
          "UserPhoneBook": [],
          "SocialMediaList": [
            {"ID": "35", "InstituteId": "2", "Code": "LI", "Url": "https:\/\/www.linkedin.com\/", "Description": ""},
            {"ID": "36", "InstituteId": "2", "Code": "FB", "Url": "https:\/\/www.facebook.com", "Description": ""},
            {"ID": "37", "InstituteId": "2", "Code": "TW", "Url": "https:\/\/www.x.com", "Description": ""},
            {"ID": "38", "InstituteId": "2", "Code": "IG", "Url": "https:\/\/www.Instagram.com\/", "Description": ""},
            {"ID": "39", "InstituteId": "2", "Code": "TH", "Url": "https:\/\/threads.com", "Description": ""},
            {"ID": "40", "InstituteId": "2", "Code": "BS", "Url": "", "Description": ""},
          ],
          "ExchangeContactInfoEnabled": true,
          "UserBio": "Tester",
          "PresenterRole": "QA",
          "WorkshopList": [
            {"PresenterRole": "QA", "WorkshopID": "10337", "WorkshopTitle": "Regression Testing"},
            {"PresenterRole": null, "WorkshopID": "10338", "WorkshopTitle": "Regression Testing [19-02-2026]"},
          ],
          "ProfileRingCode": null,
        },

        {
          "ComponentType": "User",
          "ComponentID": "15",
          "FirstName": "Jyoti",
          "LastName": "A",
          "EmailID": "jyoti_qa@neeltesting.com",
          "ProfilePicture": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/2\/public\/f29c17aa-54ce-4385-b4c1-8bbd91f6cd8a.png?expiry=1773417453&signature=WU56Lzc3UmZYN0VKY2g5K0VWRXU0dzVJZmVJUFByZ3UyQ2RQdzZvZTczcz18Q29tbXVuaWNhdGlvbg%3D%3D&b=7621",
          "UserChatEnabled": true,
          "IsUserOnline": true,
          "Description": "Tester",
          "Position": "QA",
          "Organization": "QA",
          "UserPhoneBook": [],
          "SocialMediaList": [
            {"ID": "35", "InstituteId": "2", "Code": "LI", "Url": "https:\/\/www.linkedin.com\/", "Description": ""},
            {"ID": "36", "InstituteId": "2", "Code": "FB", "Url": "https:\/\/www.facebook.com", "Description": ""},
            {"ID": "37", "InstituteId": "2", "Code": "TW", "Url": "https:\/\/www.x.com", "Description": ""},
            {"ID": "38", "InstituteId": "2", "Code": "IG", "Url": "https:\/\/www.Instagram.com\/", "Description": ""},
            {"ID": "39", "InstituteId": "2", "Code": "TH", "Url": "https:\/\/threads.com", "Description": ""},
            {"ID": "40", "InstituteId": "2", "Code": "BS", "Url": "", "Description": ""},
          ],
          "ExchangeContactInfoEnabled": true,
          "UserBio": "Tester",
          "PresenterRole": "QA",
          "WorkshopList": [
            {"PresenterRole": "QA", "WorkshopID": "10337", "WorkshopTitle": "Regression Testing"},
            {"PresenterRole": null, "WorkshopID": "10338", "WorkshopTitle": "Regression Testing [19-02-2026]"},
          ],
          "ProfileRingCode": null,
        },
      ],
      "DynamicFields": [
        {"FieldCode": "ProfilePicture", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "JY_Profile Picture", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Required", "RegularExpression4Web": "", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "FileUpload"},
        {"FieldCode": "MiddleName", "IsMandate": false, "IsReadonly": false, "RegularExpression": "^(.){0,150}", "FieldTitle": "Middle Name", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter middle name", "RegularExpression4Web": "\/^(.){0,150}\/gi", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "EnglishName", "IsMandate": false, "IsReadonly": false, "RegularExpression": "^(.){0,250}", "FieldTitle": "English Name", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "\/^(.){0,250}\/gi", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "DOB", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Student DOB", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "Calendar"},
        {"FieldCode": "DigitalSignature", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Digital Signature", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "DigiSign"},
        {
          "FieldCode": "PrimaryEmail",
          "IsMandate": true,
          "IsReadonly": false,
          "RegularExpression": "^((?=.{0,150})(([^<>()[\\]\\\\.,;:\\s@\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})))",
          "FieldTitle": "Jy Email",
          "FieldHelpText": "",
          "FieldInfo": "",
          "IsVisible": true,
          "ValidationMessage": "Enter primary email",
          "RegularExpression4Web": "\/^((?=.{0,150})(([^<>()[\\]\\\\.,;:\\s@\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})))\/",
          "FormCode": "UserProfile",
          "ComponentID": "0",
          "FieldType": "Email",
        },
        {"FieldCode": "Gender", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Gender", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "Citizenship", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Citizenship_jy", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "FirstName", "IsMandate": true, "IsReadonly": false, "RegularExpression": "^(.){0,150}", "FieldTitle": "Jy First Name", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter first name", "RegularExpression4Web": "\/^(.){0,150}\/gi", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "LastName", "IsMandate": true, "IsReadonly": false, "RegularExpression": "^(.){0,150}", "FieldTitle": "Jy Last Name", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter last name", "RegularExpression4Web": "\/^(.){0,150}\/gi", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "IsPermanentResident", "IsMandate": true, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Permanent Resident", "FieldHelpText": "Selcet options", "FieldInfo": "Select Permanent Resident options", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "RadioButton"},
        {"FieldCode": "UserBio", "IsMandate": false, "IsReadonly": false, "RegularExpression": "^([\\w-\\s]){1,1000}", "FieldTitle": "User Bio", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "\/^([\\w-\\s]){1,1000}\/gi", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "UserStudyPeriodEndDate", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Study Period End Date", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "Calendar"},
        {"FieldCode": "Organization", "IsMandate": false, "IsReadonly": false, "RegularExpression": "^(.){0,150}", "FieldTitle": "Organization", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value\u000a2 to 15 alpha numeric", "RegularExpression4Web": "\/^(.){0,150}\/gi", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "ProgramLength", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Program Length", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select program length", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "UserStudyPeriodStartDate", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Study Period Start Date", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "Calendar"},
        {"FieldCode": "IsSponsor", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Sponsor List", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "CheckBox"},
        {"FieldCode": "StartDate", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Start Date", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select start date", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "Calendar"},
        {"FieldCode": "ProgramLevel", "IsMandate": false, "IsReadonly": false, "RegularExpression": "^(.){0,25}", "FieldTitle": "Program Level", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value\u000a0 to 25", "RegularExpression4Web": "\/^(.){0,25}\/gi", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "IsStaff", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Staff Members", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "CheckBox"},
        {"FieldCode": "StudentID", "IsMandate": false, "IsReadonly": false, "RegularExpression": "^(.){0,50}", "FieldTitle": "Student id", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "\/^(.){0,50}\/gi", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "UserCoopInternshipStartDate", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Coop Internship Start Date", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "Calendar"},
        {"FieldCode": "Semester", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Semester_jy", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "ProfileRing", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Profile Ring Color", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select Profile Ring Color", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "UserCoopInternshipEndDate", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Coop Internship End Date", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "Calendar"},
        {"FieldCode": "IsPresenter", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Presenter", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "CheckBox"},
        {"FieldCode": "ProgramInactiveDate", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Set Account Inactive date", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "Calendar"},
        {"FieldCode": "IsVisaConfirmed", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Is Visa Confirmed?", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select any option only alphabets", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "RadioButton"},
        {
          "FieldCode": "Position",
          "IsMandate": false,
          "IsReadonly": false,
          "RegularExpression": "^(.){0,150}",
          "FieldTitle": "Position",
          "FieldHelpText": "Position",
          "FieldInfo": "777\u000a\u000ahttp:\/\/www.google.com\u000a\u000a\u000a\u0009\u000a\u0009\u0009\u000a\u0009\u0009\u0009 \u000a\u0009\u0009\u0009 \u000a\u0009\u0009\u000a\u0009\u0009\u000a\u0009\u0009\u0009 \u000a\u0009\u0009\u0009 \u000a\u0009\u0009\u000a\u0009\u0009\u000a\u0009\u0009\u0009 \u000a\u0009\u0009\u0009 \u000a\u0009\u0009\u000a\u0009\u000a\u000a\u000asdasdASAdsD\u000a\u000a \u000a\u000aSASDSF",
          "IsVisible": true,
          "ValidationMessage": "Position",
          "RegularExpression4Web": "\/^(.){0,150}\/gi",
          "FormCode": "ProgramProfile",
          "ComponentID": "0",
          "FieldType": "TextBox",
        },
        {"FieldCode": "Program", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Program_jy", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "UserCategory", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "User Category", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "ProgramLengthType", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Program Length Type", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select program length type", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "AcademicSchool", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "AcademicSchool_jy", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "IntegrationID", "IsMandate": false, "IsReadonly": true, "RegularExpression": "", "FieldTitle": "Integration ID", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {"FieldCode": "EndDate", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "End Date", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select end date", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "Calendar"},
        {"FieldCode": "Campus", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Campus", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "IsiSupport", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Support Team", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "CheckBox"},
        {"FieldCode": "AdmitTerm", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Admit Term_jy", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "AcademicLevel", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Academic Level_jy", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "DropDown"},
        {"FieldCode": "IsExchangeUser", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Exchange User", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "RadioButton"},
        {"FieldCode": "IsiRep", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Members", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select appropriate option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "CheckBox"},
        {"FieldCode": "CoopInternshipOpted", "IsMandate": false, "IsReadonly": false, "RegularExpression": "", "FieldTitle": "Coop Internship Opted?", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Select any option", "RegularExpression4Web": "", "FormCode": "ProgramProfile", "ComponentID": "0", "FieldType": "RadioButton"},
        {"FieldCode": "StatusMessage", "IsMandate": false, "IsReadonly": false, "RegularExpression": "^[\\s\\S]{0,500}", "FieldTitle": "Status Message", "FieldHelpText": "", "FieldInfo": "", "IsVisible": true, "ValidationMessage": "Enter valid field value", "RegularExpression4Web": "\/^[\\s\\S]{0,500}\/gi", "FormCode": "UserProfile", "ComponentID": "0", "FieldType": "TextBox"},
        {
          "FieldCode": "SecondaryEmail",
          "IsMandate": false,
          "IsReadonly": false,
          "RegularExpression": "^((?=.{0,150})(([^<>()[\\]\\\\.,;:\\s@\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})))",
          "FieldTitle": "Secondary Email",
          "FieldHelpText": "",
          "FieldInfo": "",
          "IsVisible": true,
          "ValidationMessage": "Enter valid field value",
          "RegularExpression4Web": "\/^((?=.{0,150})(([^<>()[\\]\\\\.,;:\\s@\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})))\/",
          "FormCode": "UserProfile",
          "ComponentID": "0",
          "FieldType": "Email",
        },
      ],
    },
    "ProfileRingCode": "",
    "AttachmentDetailList": [],
  },
  "WorkshopList": [],
  "UserProfileRingList": [
    {"ID": 3, "Code": "Blue", "Name": "Blue", "Description": "Blue Color Ring", "ColorCode": "#66D4DE", "LineWidth": 10, "InstituteID": "0", "BadgeFilePath": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/frames\/blue.png?expiry=1773417453&signature=TDBVcmpINU1DV3Z6RUtGTTJ3TnF3OUM1dkpZZHE4S1lDTnU3MGpTQ3BDQT18Q29tbXVuaWNhdGlvbg%3D%3D&b=4684"},
    {"ID": 2, "Code": "Green", "Name": "Green", "Description": "Green Color Ring", "ColorCode": "#00FF00", "LineWidth": 1, "InstituteID": "0", "BadgeFilePath": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/frames\/green.png?expiry=1773417453&signature=UWtLN1cxKzBRaGdHR0xGOVFSRkRWYXQ2Ly9MTDZiMVQxTDVPUXNZOEswRT18Q29tbXVuaWNhdGlvbg%3D%3D&b=5373"},
    {"ID": 4, "Code": "Orange", "Name": "Orange", "Description": "Orange Color Ring", "ColorCode": "#FFA500", "LineWidth": 1, "InstituteID": "0", "BadgeFilePath": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/frames\/orange.png?expiry=1773417453&signature=R1VHRUVQUkR5dXpFSFZIVkx4Y2d5WHE2ODNNaFYxT0wyUCs5YVgrNWNEUT18Q29tbXVuaWNhdGlvbg%3D%3D&b=6158"},
    {"ID": 1, "Code": "Red", "Name": "Red", "Description": "Red Color Ring", "ColorCode": "#FF0000", "LineWidth": 1, "InstituteID": "0", "BadgeFilePath": "https:\/\/qaiadmin.neelsystems.com\/instituteimages\/frames\/red.png?expiry=1773417453&signature=M09IeU0rckE4VzV0SEtIc0dnc1RoR0hJaXNqbXhrbkNKYkJBU1NCdmJJZz18Q29tbXVuaWNhdGlvbg%3D%3D&b=4260"},
  ],
};
